<nav id="myNavbar" class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Got the Gist? Basketball</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="http://www.tutorialrepublic.com" target="_blank">Home</a></li>
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">Basketball<b class="caret"></b></a>
                    <ul role="menu" class="dropdown-menu">
                        <li><a href="#">Rules</a></li>
                        <li><a href="#">Positions</a></li>
                        <li><a href="#">TV Experience</a></li>
                        <li><a href="#">Statistics</a></li>
                        <li><a href="#">Leagues</a></li>
                        <li><a href="#">History</a></li>
                        <li><a href="#">Fun Facts</a></li>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Glossary</a></li>
                        <li><a href="#">Sound Smart</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">NBA Overview<b class="caret"></b></a>
                    <ul role="menu" class="dropdown-menu">
                        <li><a href="#">Essentials</a></li>
                        <li><a href="#">League Format</a></li>
                        <li><a href="#">Best Players</a></li>
                        <li><a href="#">Best Teams</a></li>
                        <li><a href="#">Characters</a></li>
                        <li><a href="#">Schedule</a></li>
                        <li><a href="#">Standings</a></li>
                        <li><a href="#">Recent News</a></li>
                        <li><a href="#">Gossip</a></li>
                        <li><a href="#">Celebrity Connections</a></li>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Sound Smart</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">NBA Teams<b class="caret"></b></a>
					<ul class="dropdown-menu multi-column columns-2">
			            <div class="row">
				            <div class="col-sm-6">
					            <ul class="multi-column-dropdown">
						            <li><a href="#">Atlanta Hawks</a></li>
						            <li><a href="#">Boston Celtics</a></li>
						            <li><a href="#">Brooklyn Nets</a></li>
						            <li><a href="#">Charlotte Hornets</a></li>
						            <li><a href="#">Chicago Bulls</a></li>
						            <li><a href="#">Charlotte Hornets</a></li>
						            <li><a href="#">Cleveland Cavaliers</a></li>
						            <li><a href="#">Dallas Mavericks</a></li>
						            <li><a href="#">Denver Nuggets</a></li>
						            <li><a href="#">Detroit Pistons</a></li>
						            <li><a href="#">Golden State Warriors</a></li>
						            <li><a href="#">Houston Rockets</a></li>
						            <li><a href="#">Indiana Pacers</a></li>
						            <li><a href="#">LA Clippers</a></li>
						            <li><a href="#">LA Lakers</a></li>
					            </ul>
				            </div>
				            <div class="col-sm-6">
					            <ul class="multi-column-dropdown">
						            <li><a href="#">Memphis Grizzlies</a></li>
									<li><a href="#">Miami Heat</a></li>
									<li><a href="#">Milwaukee Bucks</a></li>
									<li><a href="#">Minnesota Timberwolves</a></li>
									<li><a href="#">New Orleans Pelicans</a></li>
									<li><a href="#">New York Knicks</a></li>
									<li><a href="#">Oklahoma City Thunder</a></li>
									<li><a href="#">Orlando Magic</a></li>
									<li><a href="#">Philadelphia 76ers</a></li>
									<li><a href="#">Phoenix Suns</a></li>
									<li><a href="#">Portland Trail Blazers</a></li>
									<li><a href="#">Sacramento Kings</a></li>
									<li><a href="#">San Antonio Spurs</a></li>
									<li><a href="#">Toronto Raptors</a></li>
									<li><a href="#">Utah Jazz</a></li>
									<li><a href="#">Washington Wizards</a></li>
					            </ul>
				            </div>
			            </div>
		            </ul>
                </li>
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">NBA Players<b class="caret"></b></a>
                    <ul role="menu" class="dropdown-menu">
                        <li><a href="#">Inbox</a></li>
                        <li><a href="#">Drafts</a></li>
                        <li><a href="#">Sent Items</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Trash</a></li>
                    </ul>
                </li>
            </ul>
            <form role="search" class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" placeholder="Search" class="form-control">
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Login</a></li>
            </ul>
        </div>
    </div>
</nav>